import unittest
from translator import Sequences


class TestTranslatorMethods(unittest.TestCase):

	def test_check_input_seq(self):
		self.assertEqual("SKL", Sequences("TCGAAGCTA"))

	def test_long_sequence(self):
		self.assertEqual("DISEGVSEMGKNP*ETLKDIPLIAKVERLRLWEGQGLVKAAVSLGQSQCPSGAPSTM*SHLGAEDSWWVFCAGSGGFPESHFGDSW"+
						"PRPARGSVLHPGPPETPSPAAESCLLPWVGTTCVLTWGI*PMSTSILLFSLAPYSHSMSTFRDLGTGERVARAEYPHHQGPLTVCQTL"+
						"KYTTLPVLQMRTLRPGKVNPSGLGATGVLTD", 
						Sequences("GACATCAGTGAGGGTGTCTCAGAGATGGGCAAGAATCCTTAAGAGACCCTCAAAGATATCCCACTCATTG"+
										"CAAAGGTGGAGAGACTGAGGCTCTGGGAAGGGCAGGGCCTGGTCAAGGCCGCAGTGAGTCTGGGACAGAG"+
										"CCAGTGTCCATCAGGGGCTCCTTCTACTATGTGAAGCCACCTGGGGGCTGAAGACAGCTGGTGGGTTTTC"+
										"TGTGCAGGGTCTGGTGGTTTCCCAGAATCCCACTTCGGGGACAGTTGGCCTCGGCCTGCCAGGGGCTCTG"+
										"TCCTTCACCCTGGACCGCCTGAGACACCCAGCCCTGCAGCTGAATCCTGTCTCCTTCCCTGGGTCGGGAC"+
										"CACTTGTGTGCTCACCTGGGGGATATAGCCAATGTCCACCTCCATATTGCTGTTCTCACTGGCCCCATAC"+
										"AGCCACTCCATGTCCACATTCAGAGACCTGGGGACAGGTGAGAGGGTGGCCAGGGCCGAATACCCCCACC"+
										"ACCAAGGCCCATTAACCGTATGTCAGACTCTGAAGTACACAACTCTCCCTGTGTTACAGATGAGGACACT"+
										"GAGGCCCGGCAAGGTGAACCCAAGTGGTCTCGGGGCCACTGGGGTTTTGACAGAT"))



if __name__ == '__main__':
	unittest.main()